
const mongoose = require("mongoose");
const Review = require("./models/Review");
const User = require("./models/User");
const Product = require("./models/Product");
const dotenv = require("dotenv");

dotenv.config();

mongoose.connect(process.env.MONGODB_URL)
  .then(() => {
    console.log("Connected to DB");
    createDemoReview();
  })
  .catch((err) => console.log(err));

async function createDemoReview() {
  try {
    // 1. Get a real user and product
    const user = await User.findOne();
    const product = await Product.findOne();

    if (!user || !product) {
      console.log("Need at least one user and one product to test review creation.");
      return;
    }

    console.log(`Using User: ${user._id} (${user.username})`);
    console.log(`Using Product: ${product._id} (${product.title})`);

    // 2. Create a review manually
    const reviewData = {
      user: user._id,
      product: product._id,
      rating: 5,
      comment: "This is a test review generated by script.",
      orderId: "test-order-123"
    };

    const newReview = new Review(reviewData);
    const savedReview = await newReview.save();
    console.log("Review saved successfully:", savedReview);

    // 3. Verify fetching
    const reviews = await Review.find({ user: user._id });
    console.log(`Fetched ${reviews.length} reviews for user.`);

  } catch (err) {
    console.error("Error creating review:", err);
  } finally {
    mongoose.connection.close();
  }
}
